# This rule is not used by the project volume-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over pdok.nl.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: volume-operator
    app.kubernetes.io/managed-by: kustomize
  name: volumepopulator-admin-role
rules:
- apiGroups:
  - pdok.nl
  resources:
  - volumepopulators
  verbs:
  - '*'
- apiGroups:
  - pdok.nl
  resources:
  - volumepopulators/status
  verbs:
  - get
