---
name: lint (go)
on:
  push:
    branches:
      - master
  pull_request:
permissions:
  contents: read
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: false

      - uses: actions/checkout@v3

      - name: tidy
        uses: katexochen/go-tidy-check@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
